# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6.QtWidgets import QMainWindow, QPushButton, QLineEdit, QLabel, QVBoxLayout, QWidget, QTableWidget, QTableWidgetItem, QHBoxLayout

class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        self.setWindowTitle("Budget Planner")
        self.setFixedSize(300, 300)

        self.input_income = QLineEdit(self)
        self.input_income.setPlaceholderText("Enter monthly income")
        
        self.btn_calculate = QPushButton("Calculate Budget", self)
        self.btn_view_history = QPushButton("View History", self)

        self.result_label = QLabel("Results will appear here", self)
        self.result_label.setWordWrap(True)

        layout = QVBoxLayout()
        layout.addWidget(self.input_income)
        layout.addWidget(self.btn_calculate)
        layout.addWidget(self.btn_view_history)
        layout.addWidget(self.result_label)

        container = QWidget()
        container.setLayout(layout)
        self.setCentralWidget(container)