# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Test

on:
  push:
    branches: [ "main" ]  # Runs on pushes to 'main'
  pull_request:
    branches: [ "main" ]  # Runs on PRs targeting 'main'

jobs:
  test:
    runs-on: ubuntu-latest  # Uses a Linux virtual machine

    steps:
      - uses: actions/checkout@v4  # Checks out your repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.1"  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have one
          pip install pytest  # Example for pytest

      - name: Run tests
        run: |
          python -m pytest  # Runs pytest (adjust if using unittest)
